# networks -----------------------------------------------------
# Creates a network with the exact name inception.
# Uses the default bridge driver implicitly.

networks:
  inception:
    name: inception

# services -----------------------------------------------------
# build - build an image with a providing a path to the build 
# context (the directory containing the Dockerfile and source 
# code).

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
      args:
        SSL_CERT_FOLDER: ${SSL_CERT_FOLDER}
        SSL_KEY: ${SSL_KEY}
        SSL_CERT: ${SSL_CERT}
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: nginx
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html

# volumes -----------------------------------------------------
# device: where the data will be stored in the  machine

volumes:
  db_data:
    driver: local
    driver_opts:
      device: ${HOME}/data/mariadb
      o: bind
      type: none
  wp_data:
    driver: local
    driver_opts:
      device: ${HOME}/data/wordpress
      o: bind
      type: none
