services:

  # mariadb container
  mariadb:
    #container_name:
    build: ./requirements/mariadb/.
    env_file:
      - .env
    #networks:
    ports:
      - "5000:5000"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  # restart: on-failure
  
  wordpress:
    build: ./requirements/wordpress/.
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html

  # nginx container

# networks

#networks:

volumes:
  db_data:
  wp_data:
